data_sources:
  # Local file source
  - type: local
    path: "./data/*"
    metadata:
      description: "Local sample documents"

  # Azure Blob Storage source
  - type: azure_blob
    storage_account: "mystorageaccount"
    container: "documents"
    blob_prefix: "company-docs/"
    metadata:
      description: "Company documents in Azure Blob Storage"

  # Azure Data Lake Gen2 source
  - type: adls_gen2
    storage_account: "mydatalakeaccount"
    filesystem: "documents"
    path: "processed/"
    metadata:
      description: "Processed documents in Azure Data Lake Gen2"

  # SharePoint source - Company policies
  - type: sharepoint
    tenant_id: "your-tenant-id"
    client_id: "your-app-client-id"
    client_secret: "your-app-client-secret"
    site_url: "https://yourtenant.sharepoint.com/sites/yoursite"
    document_library: "Shared Documents"
    folder_path: "company-policies"
    max_file_size_mb: 100
    supported_extensions:
      - ".pdf"
      - ".docx"
      - ".doc"
      - ".pptx"
      - ".ppt"
      - ".xlsx"
      - ".xls"
      - ".txt"
      - ".md"
    batch_size: 50
    enable_incremental_sync: true
    metadata:
      description: "Company policies from SharePoint document library"

  # SharePoint source - HR documents
  - type: sharepoint
    tenant_id: "your-tenant-id"
    client_id: "your-app-client-id"
    client_secret: "your-app-client-secret"
    site_url: "https://yourtenant.sharepoint.com/sites/hr"
    document_library: "HR Documents"
    folder_path: ""
    max_file_size_mb: 50
    supported_extensions:
      - ".pdf"
      - ".docx"
    batch_size: 25
    enable_incremental_sync: true
    metadata:
      description: "HR documents from dedicated SharePoint site"

# Azure service configuration
azure:
  search_service: "my-search-service"
  search_index: "documents-index"
  storage_account: "mystorageaccount"
  storage_container: "content"
  openai_service: "my-openai-service"
  openai_endpoint: "https://my-openai-service.openai.azure.com/"
  openai_deployment: "text-embedding-ada-002"
  openai_model: "text-embedding-ada-002"
  openai_api_version: "2024-06-01"
  document_intelligence_service: "my-doc-intelligence"
  subscription_id: "your-subscription-id"
  tenant_id: "your-tenant-id"

# Processing options
use_integrated_vectorization: false
use_gpt_vision: false
use_acls: false
use_vectors: true
use_local_pdf_parser: false
use_local_html_parser: false
disable_batch_vectors: false
default_category: "general"
skip_blobs: false
verbose: true 